### ISSUE TITLE
conversion works but it removes <p> tags

### ISSUE THREAD

**Issue by ut** [Kephson/reint_ttnewsdamtofal#1]
after calling the conversion all <media> tags were succesfully converted into full working FAL links, but all p- tags were gone and all content got wrapped by one single p-tag. for example:

before conversion:

``` html
<p>some text</p>
<p>some more text</p>
<p>some more ....</p>
<p><media 213>PDF File</media></p>
```

after conversion:

``` html
<p>some text some more text some more....</p>
<p><a class="download" target="_blank" title="PDF File" href="fileadmin/user_upload/----.pdf">PDF File</a></p>
```

**Comment by Kephson** [comment]
Thanks for your reply, I will test this issue and fix it.

**Comment by Kephson** [comment]
I tested with

``` html
<p>some text</p>
<p>some more text</p>
<p>some more ....</p>
<p><media 1>PDF File</media></p>
```

and the output is:

``` html
<p>some text</p>
<p>some more text</p>
<p>some more ....</p>
<p><link file:1 _blank download "PDF File">PDF File</link></p>
```

This is correct and i can not follow this issue.
Is there a special constellation of your TYPO3 site?
Please give me feedback.

**Comment by Kephson** [comment]
No reply, so issue was closed.

**Comment by ut** [comment]
I've been on vacation. I took a second look, it's not about removing `<p>` tags, but newlines (which are are rendered by Typo 3 with a `<p>`  wrap) I have seen it on two different Typo3 installations (4.5 > 6.2). I will make a pull request with a possible fix, that worked well on these installations.
