### ISSUE TITLE
simple_html_dom can't handle Typo3 link syntax

### ISSUE THREAD

**Issue by ut** [Kephson/reint_ttnewsdamtofal#3]
Hey Ephraim, here is a bit more severe problem: The library used for dom parsing can't handle typo3 link syntax. any found `<LINK http://typo3.org>Typo3</link>` will be converted to `<link http:>Typo3<link>`.  ((Since the library will everything thrown away after the string "http:"))

According to the simple_html_dom API there is no way to mark a tag as "ignore" or "skip". My inspection of the code did not give any other approaches to override this behaviour.

**Comment by ut** [comment]
To be more precise: It is not the "http:" but the double-slashes "//" which causes that everything after  "http:" gets omitted

**Comment by Kephson** [comment]
Hm, ok. In my case there were no need to convert tags like `<LINK http://typo3.org>Typo3</link>`. In which case do you have tags like this?

**Comment by ut** [comment]
I'm not sure if I got your question right. But we have links in the typical Typo3-Syntax written with the scheme `<LINK http://typo3.org>Typo3</link>` (the syntax is created by RTE). All those links get invalid after running reint_ttnewsdamtofal, because simple_html_dom can't handle them. Funny is the the irregular link syntax <MEDIA... can be handled (with internal linktarget) but no construct with a "http://" in it, like external Typo3 links.

**Comment by Kephson** [comment]
Ok, I will search for a solution to fix this problem, this is really strange. Maybe there is another library which I can use to parse the HTML in a better way.

**Comment by ut** [comment]
As a quick and dirty workaround, we removed the double slahes "//" from the external links before simple_html_dom parsing and insert it after the parsing (e.g. `http://www.domain.com` > `http:www.domain.com` > `http://www.domain.com`). 

This is really silly and no reasonable fix, but it worked (all links are converted without beeing destroyed) and perhaps it points you to the problem in simple_html_dom.

**Comment by Kephson** [comment]
Ok, I will have a look for a quick fix.

**Comment by Kephson** [comment]
dirty fix integrated in 1.0.4. At the moment I have no other idea and this works.
